# Generated by Django 4.2 on 2023-04-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_useraccount_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='dob',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(default='Male', max_length=8),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
