# Generated by Django 4.2 on 2023-04-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_useraccount_dob_useraccount_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
