# Generated by Django 4.2 on 2023-04-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_useraccount_dob_alter_useraccount_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='register',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
