# Generated by Django 4.1.5 on 2023-05-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_tasks_project_alter_work_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="work",
            old_name="file",
            new_name="files",
        ),
        migrations.AlterField(
            model_name="work",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
