# Generated by Django 4.1.5 on 2023-05-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_useraccount_project_alter_work_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
