# Generated by Django 4.1.5 on 2023-05-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_work_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tasks",
            name="max_score",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="tasks",
            name="score_obtained",
            field=models.IntegerField(default=0),
        ),
    ]
