# Generated by Django 4.1.5 on 2023-05-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_tasks_completed_tasks_max_score_tasks_score_obtained"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasks",
            options={"ordering": ["-due_date"]},
        ),
        migrations.AlterField(
            model_name="tasks",
            name="score_obtained",
            field=models.IntegerField(null=True),
        ),
    ]
