# Generated by Django 4.1.5 on 2023-05-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_remove_useraccount_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="oldprojects",
            name="guide",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="oldprojects",
            name="std1",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="oldprojects",
            name="std2",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="oldprojects",
            name="std3",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="oldprojects",
            name="std4",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
