# Generated by Django 4.1.5 on 2023-05-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_oldprojects_guide_oldprojects_std1_oldprojects_std2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="oldprojects",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
