# Generated by Django 4.1.5 on 2023-05-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_oldprojects_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="project",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="projects",
            field=models.ManyToManyField(related_name="users", to="main.project"),
        ),
    ]
