# Generated by Django 4.1.5 on 2023-05-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_remove_useraccount_project_useraccount_projects"),
    ]

    operations = [
        migrations.RenameField(
            model_name="useraccount",
            old_name="projects",
            new_name="project",
        ),
    ]
