# Generated by Django 4.1.5 on 2023-06-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_mark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="score_obtained",
        ),
    ]
