# Generated by Django 4.1.5 on 2023-06-09 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_remove_tasks_score_obtained"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mark",
            name="assignment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marks",
                to="main.tasks",
            ),
        ),
        migrations.AlterField(
            model_name="mark",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
